# Generated by Django 5.2.5 on 2025-09-28 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='user',
        ),
    ]
